version: "3"
services:
  server:
    build: .
    image: dauleduc2/book-shop:latest
    ports:
      - 80:8080
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456
    volumes:
      - ./data:/data
    ports:
      - 1533:1433
